server.port: 3000

spring:
  application:
    name: video-store-service
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  profiles:
    active: ${PROFILE:test}
  gson:
    pretty-printing: true
  jackson:
    serialization:
      INDENT_OUTPUT: true
      write-dates-as-timestamps: false

  datasource:
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:3259}/${DATABASE_NAME:video_store}
    username: ${DATABASE_USER:vs}
    password: ${DATABASE_PASSWORD:vs}

  jpa:
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
      dialect: org.hibernate.dialect.PostgreSQLDialect

  rabbitmq:
    host: ${MESSAGING_HOST:rabbitmq}
    port: ${MESSAGING_PORT:5672}
    virtual-host: ${MESSAGING_VHOST:/}
    username: ${MESSAGING_USER:guest}
    password: ${MESSAGING_PASSWORD:guest}
  sql:
    init:
      platform: postgres

logging:
  traceable:
    http.mdc-cleaner-disabled: true
  level:
    "org.springframework.amqp.rabbit.listener.ConditionalRejectingErrorHandler": warn

swagger:
  package-scan: org.videostore.controller
  title: API
  description: Doc API
  version: 1.0-SNAPSHOT